x-airflow-common:
  &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
    args:
      - AIRFLOW_VERSION=${AIRFLOW_VERSION:-latest}
      - AIRFLOW_USER=${AIRFLOW_USER:-airflow}
      - AIRFLOW_PASSWORD=${AIRFLOW_PASSWORD:-airflow}
      - AIRFLOW_HOME=${AIRFLOW_HOME:-/opt/airflow}
      - AIRFLOW_UID=${AIRFLOW_UID:-50000}
  env_file:
    - .env
  volumes:
    - ${AIRFLOW_PROJ_DIR:-.}/dags:${AIRFLOW_HOME:-/opt/airflow}/dags
    - ${AIRFLOW_PROJ_DIR:-.}/logs:${AIRFLOW_HOME:-/opt/airflow}/logs
    - ${AIRFLOW_PROJ_DIR:-.}/plugins:${AIRFLOW_HOME:-/opt/airflow}/plugins
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    &airflow-common-depends-on
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:13
    restart: always
    env_file:
      - .env    
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-db-volume:/opt/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

  webserver:
    <<: *airflow-common
    command: webserver
    restart: always
    env_file:
      - .env
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"']
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-init:
    <<: *airflow-common
    env_file:
      - .env
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}/.env:${AIRFLOW_HOME:-/opt/airflow}/.env
      - ${AIRFLOW_PROJ_DIR:-.}:/sources
    entrypoint: /bin/bash
    command: 
      - -c
      - |
        mkdir -p ${AIRFLOW_PROJ_DIR:-.}/dags ${AIRFLOW_PROJ_DIR:-.}/plugins ${AIRFLOW_PROJ_DIR:-.}/logs
        if ! grep '^AIRFLOW_UID=[0-9]' .env ; then 
          echo -e "AIRFLOW_UID=$$(id -u)\n" >> .env
        fi
        airflow db init
        airflow db upgrade
        airflow users create \
            --role $ROLE \
            --username $USER \
            --password $PASSWORD \
            --firstname $FIRST \
            --lastname $LAST \
            --email $EMAIL
    depends_on:
      <<: *airflow-common-depends-on

  airflow-cli:
    <<: *airflow-common
    profiles:
      - debug
    env_file:
      - .env
    environment:
      CONNECTION_CHECK_MAX_COUNT: "0"
    command:
      - bash
      - -c
      - airflow

volumes:
  postgres-db-volume:
